### PR TITLE
fix(openshift-image-registry): fix #596: Add mock data for test page and cleanup some small code smells

### LINKED ISSUE #596: Reduce code smells in Openshift image registry plugin
Part of: #583

Investigate code smells in the Tekton plugin and fix them via a PR or explained why they should be dismissed as irrelevant.

See this plugin folder and respective code smells column here:
https://sonarcloud.io/code?id=janus-idp_backstage-plugins&selected=janus-idp_backstage-plugins%3Aplugins

### PR DESCRIPTION
**Pull request by jerolimov**
Fix #596: Cleanup [3 small code smells](https://sonarcloud.io/code?id=janus-idp_backstage-plugins&selected=janus-idp_backstage-plugins%3Aplugins%2Fopenshift-image-registry) reported by sonarcloud:

* https://sonarcloud.io/code?id=janus-idp_backstage-plugins&selected=janus-idp_backstage-plugins%3Aplugins%2Fopenshift-image-registry%2Fsrc%2Fcomponents%2FOcirImages%2FOcirImagesCard.tsx
  * Used the tag as key since duplicates should happen because each tag refers to a resource name
* https://sonarcloud.io/code?id=janus-idp_backstage-plugins&selected=janus-idp_backstage-plugins%3Aplugins%2Fopenshift-image-registry%2Fsrc%2Fcomponents%2FOcirImages%2FOcirImagesCards.tsx
  * Cleanuped the usage of `toggleDrawer` by using more explicit props to close the drawer.
* https://sonarcloud.io/code?id=janus-idp_backstage-plugins&selected=janus-idp_backstage-plugins%3Aplugins%2Fopenshift-image-registry%2Fsrc%2Fcomponents%2FOcirImages%2FOcirImageSidebar.tsx
  * Used the tag as key since duplicates should happen because each tag refers to a resource name

I also added some mock data so that the UI test page can be used to confirm that the plugin still works:

image

I've also tested it on backstage app with a real cluster:

https://github.com/janus-idp/backstage-plugins/assets/139310/acc7f0cf-0af4-4569-b6ed-8a0788b7298b

### CODE REVIEW

File: plugins/openshift-image-registry/src/components/OcirImages/OcirImagesCard.tsx [hunk 1]
```diff
@@ -87,7 +87,7 @@ export const OcirImagesCard = ({
           </Typography>
           {imageStream.tags?.length
             ? imageStream.tags.map((tag: string, i: number) => (
-                <Chip size="small" label={tag} key={i} />
+                <Chip size="small" label={tag} key={i} /> // NOSONAR
```
Comment (invincibleJai) [inline plugins/openshift-image-registry/src/components/OcirImages/OcirImagesCard.tsx:90]: can we make use of a tag here over the index?

Comment (jerolimov) [reply plugins/openshift-image-registry/src/components/OcirImages/OcirImagesCard.tsx:90]: I don't want to touch it because I didn't know if a tag could be listed multiple times. It would be unexpected, and we might want to drop the duplicates then as well... I can do that change.

File: plugins/openshift-image-registry/src/components/OcirImages/OcirImageSidebar.tsx [hunk 2]
```diff
@@ -133,7 +133,7 @@ export const OcirImageSidebar = ({
             </Typography>
             {imageStream.tags?.length
               ? imageStream.tags.map((tag: string, i: number) => (
-                  <Chip size="small" label={tag} key={i} />
+                  <Chip size="small" label={tag} key={i} /> // NOSONAR
```
Comment (invincibleJai) [inline plugins/openshift-image-registry/src/components/OcirImages/OcirImageSidebar.tsx:136]: similar, can we make use of a tag here over the index?

Comment (jerolimov) [reply plugins/openshift-image-registry/src/components/OcirImages/OcirImageSidebar.tsx:136]: Oh thanks GitHub, missed that before. Used the tag here now also as key.

**Review by invincibleJai — APPROVED** [review]
LGTM
